{% set version = "0.5.0" %}

package:
  name: ocdc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/ocdc/ocdc-{{ version }}.tar.gz
  sha256: 901a78d5941140b80012d3045c5e94bfdb41550a799d877f4231d91ec89e57a4

build:
  entry_points:
    - ocdc = ocdc.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - packaging <24
    - pydantic

test:
  imports:
    - ocdc
  commands:
    - pip check
    - ocdc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mdwint/ocdc
  summary: A changelog formatter for "people", neat freaks, and sloppy typists.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
